### PR TITLE
Add PageLoad plugin for measuring page generation times on the command line

### PR DESCRIPTION
**Pull request by perlDreamer**
I've found this pretty handy for doing asset rendering measurements on the command line.  Would you consider adding it to core WGDev?

### CODE REVIEW

**Comment by perlDreamer** [comment]
I'm not sure what you meant by:

"Trapping then ignoring all errors seems a bit goofy."

But if you clue me in I'll fix it, too.

**Comment by haarg** [comment]
Mainly that if an error happens it should probably be reported, and maybe skip the steps after it.  I don't have strong feelings about that, but if it could be improved that would be great.

**Comment by haarg** [comment]
I caught your note on IRC about cache permissions issues.

Is that something you think should be solved within this plugin, or would you prefer a more global fix?

Also, testing the effects of caching would be a nice thing to add to this plugin at some point.

**Comment by perlDreamer** [comment]
A global fix would help every plugin, so I say go for it.  If you'll do 
that, then I have no more hesitation about adding this plugin.

**Pull request closed without merging**
